package statemachine.utils;

public enum StateParameters {
	INIT, CLICK_LOAD, CLICK_SAVE, CLICK_CREATE_AGENT, CLICK_ADD_ROUND, CLICK_START_TOURNAMENT, CLICK_AGENTS_LISTVIEW, CLICK_ROUNDS_LISTVIEW, CLICK_BACK, CREATE_AGENT, CREATE_ROUND, CLICK_CLEAR_AGENTS, CLICK_CLEAR_ROUNDS
}
