package statemachine.utils;


public enum StateName {
	START, DASHBOARD, AGENT_CREATION, ROUND_CREATION, TOURNAMENT_PLAYING, TOURNAMENT_FINISHED, LOADING_TOURNAMENT, SAVING_TOURNAMENT, SAVING_DATA, CLICK_AGENTS_LISTVIEW, TOURNAMENT_PHASE;
}