package gui.utils;
public class GUIText {
	public static final String SETUP = "Setup";
	public static final String BUTTON_NEXT = "Next";
	public static final String CONFIRMATION_NO = "No";
	public static final String CONFIRMATION_YES = "Yes";
	public static final String BACK_BUTTON = "Back";
	public static final String SUBMIT = "Submit";
	public static final String SELECT_FILE = "Select file";
	public static final String DASHBOARD = "Dashboard";
	public static final String LOAD_TOURNAMENT = "Load tournament";
	public static final String SAVE_TOURNAMENT = "Save tournament";
	public static final String START_TOURNAMENT_BUTTON = "Start";
	public static final String AGENTS_LISTVIEW_LABEL = "Agents";
	public static final String ROUND_LISTVIEW_LABEL = "Rounds";
	public static final String ADD_AGENT_BUTTON = "Add agents";
	public static final String ADD_ROUND_BUTTON = "Add rounds";
	public static final String STRATEGY_MENU_BUTTON = "Strategy";
	public static final String STRATEGY_TEXT_FIELD_LABEL = "Choose a strategy";
	public static final String AGENT_NAME_TEXT_FIELD_LABEL = "Agent name";
	public static final String CREATE_AGENT_BUTTON = "Create agent";
	public static final String GAME_MENU_BUTTON = "Select game";
	public static final String CREATE_ROUND_BUTTON = "Create round";
	public static final String GAME_MENU_BUTTON_LABEL = "Select a game";
	public static final String TOURNAMENT_PLAYING_TEXT = "Waiting for tournament to finish...";
	public static final String CREATE_AGENT_HEADING = "Create Agent";
	public static final String CREATE_ROUND_HEADING = "Create Round";
	public static final String ADDITIONAL_PARAMETERS_LISTVIEW = "Additional parameters";
	public static final String STRATEGY_NAME_LISTVIEW = "Strategy";
	public static final String AMOUNT_LISTVIEW = "Amount";
	public static final String GAME_NAME_LISTVIEW = "Game";
	public static final String CLEAR_AGENTS_BUTTON = "Clear agents";
	public static final String CLEAR_ROUNDS_BUTTON = "Clear rounds";
	public static final String REMOVE_SELECTED_AGENT = "Remove selected";
	public static final String REMOVE_SELECTED_ROUND = "Remove selected";
	public static final String BROWSE_STRATEGY_BUTTON_LABEL = "Browse strategies";
	public static final String AMOUNT_LABEL = "Amount";
}
